accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'


urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.user_logout, name='logout'),
    path('signup', views.SignUpView.as_view(), name='signup'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<str:quality>/book/<int:id>', views.BookDetailView.as_view(), name='book_detail'),
    path('<str:quality>/music/<int:id>', views.SongDetailView.as_view(), name='music_detail'),
    path('<str:quality>/video/<int:id>', views.VideoDetailView.as_view(), name='video_detail'),
    path('<str:quality>/podcast/<int:id>', views.PodcastDetailView.as_view(), name='podcast_detail'),
    path('about-us', views.AboutUsView.as_view(), name='about_us'),
]

with_me/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('core.urls', namespace='core'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):

    age = models.PositiveSmallIntegerField(verbose_name='سن', null=True, blank=True)

    class Meta:
        ordering = ['-date_joined']
        verbose_name = 'کاربر'
        verbose_name_plural = 'کاربر ها'

    def __str__(self):
        return f'{self.username}'

accounts/forms.py
from django import forms
from django.contrib.auth.password_validation import validate_password
from .models import User

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if len(username) < 4:
            raise forms.ValidationError('طول نام کاربری بالای ۴ کاراکتر باشد')
        elif len(username) > 30:
            raise forms.ValidationError('طول نام کاربری کمتر از ۳۰ کاراکتر باشد')

        return username


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=30,widget=forms.TextInput(attrs={'autocomplete':'off'}))
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        user = User.objects.filter(username=username).exists()
        if user:
            raise forms.ValidationError('نام کاربری با این اسم ثبت شده است.')
        if len(username) < 4:
            raise forms.ValidationError('طول نام کاربری بالای ۴ کاراکتر باشد')
        elif len(username) > 30:
            raise forms.ValidationError('طول نام کاربری کمتر از ۳۰ کاراکتر باشد')
        return username

    def clean_password(self):
        password = self.cleaned_data.get('password')
        try:
            validate_password(password)
        except forms.ValidationError as e:
            raise forms.ValidationError(e)
        return password

accounts/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views.generic import View
from .forms import LoginForm, SignUpForm
from django.contrib.auth import authenticate, login, logout
from .models import User



class LoginView(View):

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('core:home')
        return super().dispatch(request, *args, **kwargs)
    def get(self, request):
        form = LoginForm()
        return render(request, 'accounts/login.html', {'form':form})
    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                login(request, user)
                return redirect('core:home')
            message = 'Login failed!'
        return render(request, 'accounts/login.html', context={'form': form})


class SignUpView(View):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('core:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = SignUpForm()
        return render(request, 'accounts/sing-in.html', {'form': form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = User.objects.create(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            user.save()
            login(request, user)
            return redirect('core:home')
        return render(request, 'accounts/sing-in.html', context={'form': form})


def user_logout(request):
    logout(request)
    return redirect('core:home')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
{% block head %}
	<head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Project</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
        <link rel="stylesheet" href="{% static '/css/login.css'%}" />
    </head>
<body>
{% endblock %}
    {% block header %}
    {% endblock %}
    {% block content %}
        <section class="login_user">
            <div class="container">
                <div class="content">
                    <div class="content_img">
                        <img src="{% static 'img/sea.jpeg' %}" alt="" class="img_login">
                    </div>

                    <div class="content_login_boxs">
                        <form action="" class="form" autocomplete="on" method="post">
                            {% csrf_token %}
                            <h4 class="login_header_titel">ورود به حساب کاربری</h4>
                            <div class="content_login_box">
                                <div class="login_sigh_in_linl"><a href="{% url 'accounts:signup' %}" class="link">ثبت نام</a> | <a href="{% url 'accounts:login' %}" class="link">ورود</a></div>
                                 <label for="username" class="label_user"></label>
                                 <input type="text" class="input_user" placeholder="نام کاربری " name="username" id="username" required autofocus>
                                 <br>
                                 <label for="password" class="label_pass"></label>
                                 <input type="password" class="input_pass" placeholder="رمز عبور" id="password" name="password" required>
                                 <h5 class="recovery_password">رمز خود را فراموش کردید؟<a href="" class="password_recovery_link">کلیک کنید </a></h5>
                                 <div class="login_buttom">
                                     <button type="submit" class="btm_login"><a href="" class="btm_login_link">ورود</a></button>
                                     <div class="sign_in_in_login"> ثبت نام نکردید؟برای ثبت نام <a href="{% url 'accounts:signup' %}" class="sing_in_link">کلیک کنید</a></div>
                                    </div>
                            </div>
                        </form>

                        <div class="caption">
                            <p>ثبت نام شما به معنای پذیرش قوانین و مقررات *with-me* است.</p>
                        </div>

                    </div>
                </div>
            </div>
        </section>

{#        <script src="scripts/app.js"></script>#}
{% endblock %}
{% block footer %}{% endblock %}
</body>

</html>

accounts/templates/accounts/sing-in.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
{% block head %}
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Project</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
        <link rel="stylesheet" href="{% static 'css/sing-in.css' %}" />
    </head>
{% endblock %}
<body>
    {% block header %}
    {% endblock %}
{% block content %}
        <section class="login_user">
            <div class="container">
                <div class="content">

                    <div class="content_img">
                        <img src="{% static 'img/hawai.jpeg' %}" alt="" class="img_login">
                    </div>

                    <div class="content_login_boxs">
                        <form action="" class="form" autocomplete="off" method="post">
                            {% csrf_token %}
                            <h4 class="login_header_titel">ثبت نام کاربر</h4>
                            <div class="content_login_box">
                                <div class="login_sigh_in_linl"><a href="{% url 'accounts:signup' %}" class="link">ثبت نام</a> | <a href="{% url 'accounts:login' %}" class="link">ورود</a></div>
                                 <label for="username" class="label_user"></label>
                                {% if form.username.errors %}{{ form.username.errors }}{% endif %}
                                 <input type="text" class="input_user" placeholder="نام کاربری " name="username" id="username" required autofocus>
                                 <br>
                                 <label for="password" class="label_pass"></label>
                                 {% if form.password.errors %}{{ form.password.errors }}{% endif %}
                                 <input type="password" class="input_pass" placeholder="رمز عبور" id="password" name="password" required>

                                 <div class="login_buttom">
                                     <button type="submit" class="btm_login">ثبت نام</button>
                                    </div>
                            </div>
                      </form>

                        <div class="caption">
                            <p>ثبت نام شما به معنای پذیرش قوانین و مقررات *with-me* است.</p>
                        </div>

                    </div>
                </div>
            </div>
        </section>
{#        <script src="scripts/app.js"></script>#}
{% endblock %}
{% block footer %}{% endblock %}
    </body>
</html>