accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'


urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.user_logout, name='logout'),
    path('signup', views.SignUpView.as_view(), name='signup'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<str:quality>/book/<int:id>', views.BookDetailView.as_view(), name='book_detail'),
    path('<str:quality>/music/<int:id>', views.SongDetailView.as_view(), name='music_detail'),
    path('<str:quality>/video/<int:id>', views.VideoDetailView.as_view(), name='video_detail'),
    path('<str:quality>/podcast/<int:id>', views.PodcastDetailView.as_view(), name='podcast_detail'),
    path('about-us', views.AboutUsView.as_view(), name='about_us'),
]

with_me/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('core.urls', namespace='core'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from accounts.models import User
from django.utils.text import slugify
class Feeling(models.Model):
    CHOICES = (
        ('khosh', 'خوشحال'),
        ('khoob', 'خوب'),
        ('na', 'ناراحت'),
        ('asab', 'عصبانی'),
    )
    quality = models.CharField(choices=CHOICES, max_length=10, unique=True)

    def __str__(self):
        return f'{self.quality}'

class Book(models.Model):
    feeling = models.ForeignKey(Feeling, on_delete=models.PROTECT, related_name='books')
    image = models.ImageField(upload_to='books/images/', verbose_name='عکس')
    name = models.CharField(max_length=60)
    description = models.TextField(max_length=1000)
    author = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['-created_at']
class Podcast(models.Model):
    feeling = models.ForeignKey(Feeling, on_delete=models.PROTECT, related_name='podcast')
    audio = models.FileField(upload_to='audios/audios/')
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='audios/images/')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    def __str__(self):
        return f'{self.name}'
    class Meta:
        ordering = ['-created_at']

class Score_User(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='podcast_scores')
    podcast = models.ForeignKey(Podcast, on_delete=models.CASCADE, related_name='scores')
    score = models.PositiveSmallIntegerField()

class PodcastComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    podcast = models.ForeignKey(Podcast, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')
    text = models.CharField(max_length=300, verbose_name='متن')
    reply = models.ForeignKey('self', related_name='replies', on_delete=models.CASCADE, null=True, blank=True, verbose_name='ریپلای')
    is_published = models.BooleanField(default=False, verbose_name='منتشر')

    def __str__(self):
        return f"{self.user.username}{self.id}"

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنت پادکست ها'

class SongComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE ,verbose_name='کاربر')
    song = models.ForeignKey('Song', on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')
    text = models.CharField(max_length=300, verbose_name='متن')
    reply = models.ForeignKey('self', related_name='replies', on_delete=models.CASCADE, null=True, blank=True, verbose_name='ریپلای')
    is_published = models.BooleanField(default=False, verbose_name='منتشر')

    def __str__(self):
        return f"{self.user.username}{self.id}"

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنت اهنگ ها'


class Video(models.Model):
    feeling = models.ForeignKey(Feeling, on_delete=models.PROTECT, related_name='videos')
    image = models.ImageField(upload_to='videos/images/')
    video = models.FileField(upload_to='videos/')
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['-created_at']


class Song(models.Model):
    feeling = models.ForeignKey(Feeling, on_delete=models.PROTECT, related_name='podcasts')
    name = models.CharField(max_length=50)
    audio = models.FileField(upload_to='songs/audios/')
    image = models.ImageField(upload_to='songs/images/')
    singer = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['-created_at']

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
# TODO :  Debug, 8 ta video, Bucket, Deploy
from django.shortcuts import get_object_or_404
from accounts.models import User
from .models import *
import random
class HomeView(View):
    def get(self, request):
        if request.user.is_authenticated:
            user = User.objects.get(username=request.user.username)
        else:
            user = None
        khosh = Feeling.objects.get(quality='khosh')
        khoob = Feeling.objects.get(quality='khoob')
        na = Feeling.objects.get(quality='na')
        asab = Feeling.objects.get(quality='asab')
        return render(request, 'core/home.html', {'user' : user, 'khosh':khosh, 'khoob':khoob, 'na':na, 'asab':asab})
class BookDetailView(View):
    def get(self, request, quality, id):
        random_num = random.randint(0,12)
        feeling = get_object_or_404(Feeling, quality=quality)
        book = get_object_or_404(Book, feeling=feeling, id=id)
        books = Book.objects.all()[random_num:random_num + 4]
        return render(request, 'core/book.html', {'book' : book, 'books': books})

class SongDetailView(View):
    def get(self, request, quality, id):
        random_num = random.randint(0,12)
        feeling = get_object_or_404(Feeling, quality=quality)
        song = get_object_or_404(Song, feeling=feeling, id=id)
        songs = Song.objects.all()[random_num:random_num + 4]
        return render(request, 'core/song.html', {'song': song, 'songs':songs})

class PodcastDetailView(View):
    def get(self, request, quality, id):
        random_num = random.randint(0,12)
        feeling = get_object_or_404(Feeling, quality=quality)
        podcast = get_object_or_404(Podcast, feeling=feeling, id=id)
        podcasts = Podcast.objects.all()[random_num:random_num + 4]
        return render(request, 'core/podcast.html', {'podcast': podcast, 'podcasts':podcasts})

class VideoDetailView(View):
    def get(self, request, quality, id):
        random_num = random.randint(0,12)
        feeling = get_object_or_404(Feeling, quality=quality)
        video = get_object_or_404(Video, feeling=feeling, id=id)
        videos = Video.objects.all()[random_num:random_num + 4]
        return render(request, 'core/video.html', {'video': video, 'videos':videos})

class AboutUsView(View):
    def get(self, request):
        return render(request, 'core/about-us.html')

core/templates/core/book.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
{% block head %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/books.css' %}">
</head>
{% endblock %}
<body>
{% block content %}
    <main class="main">
        <div class="container">
            <section class="books">
                <div class="book">
                    <div class="content">
                        <h1>{{ book.name }}</h1>
                        <h3>{{ book.author }}</h3>
                         <p>{{ book.description }}</p>
                    </div>
                    <div class="images">
                        <img src="{{ book.image.url }}" alt="book" class="image">
                    </div>
                </div>
                <h1 style="margin-top: 5rem;margin-bottom: 3rem;">کتاب های بیشتر</h1>
                <div class="more_books">
                    {% for boo in books %}
                    	<div class="box">
                        <div class="simages">
                            <a href="{% url 'core:book_detail' boo.feeling boo.id %}"><img src="{{ boo.image.url }}" alt="book" class="simage"></a>
                        </div>
                        <h3>{{ boo.name }}</h3>
{#                        <p style="margin-top: -3px;">{{ boo.description | truncatewords:7 }}</p>#}
                        </div>
                    {% endfor %}
                </div>
            </section>
        </div>
    </main>
{% endblock content %}
</body>
</html>

core/templates/core/home.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
{% block head %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/main_page.css' %}">
</head>
{% endblock %}
<body>
{% block header %}
	<header class="header">
        <div class="container">
            <section class="header_top">
                <div class="nav">

                    <ul class="menu">
                        <div class="nav_logo">
                        <img style="width: 70px;height: 70px" src="{% static 'img/with_me1.png' %}" alt="" class="nav_logo_img">
                        </div>
                        <li class="menu_item"><a href="{% url 'core:home' %}" class="menu_item_link">صفحه اصلی</a></li>
                        <li class="menu_item"><a href="{% url 'core:about_us' %}" class="menu_item_link" >درباره ما</a></li>
                    </ul>
                </div>
                {% if user.is_authenticated %}
                    <a href="{% url 'accounts:logout' %}" class="heder_link">خروج</a>
                {% else %}
                <a href="{% url 'accounts:login' %}" class="heder_link">ورود</a>
                {% endif%}
            </section>
        </div>
    </header>
{% endblock header %}
{% block content %}
    <main class="main">
        <div class="container">
            <section class="main_header">
                <div class="main_header_content">
                    <h2 class="main_titel"> With Me</h2>
                    <p class="main_txt"> برای دوستی با شما طراحی شده است، که از طریق فیلم ها ، کتاب ها ، آهنگ ها و پادکست سعی می کند با شما ارتباط برقرار کند تا حال و آینده شما را بهتر کند</p>
                    <a href="#category" class="main_button">بزن بریم</a>
                </div>
                <div class="main_header_imgs">
                    <img src="{% static 'img/header-img.svg' %}" alt="" class="main_header_img">
                </div>
            </section>

            <section class="main_plan">
                <div class="main_plan_imgs">
                    <img src="{% static 'img/main-img.svg' %}" alt="" class="main_plan_img">
                </div>
                <div class="main_plan_content">
                    <h4 class="main_plan_header">برنامه ریزی</h4>
                    <p class="main_plan_txt">برای اینکه افراد بتوانید نتیجه بهتری از فعالیت های خود در روز بگیرند میتوانند که برای خود برنامه ریزی کنند <br>
                    با برنامه ریزی شما میتوانید به هدف های خود سریع تر دست پیدا کنند.<br>
                        برای مثال شما میتوانید به مدت 1 ساعت در روز صرف مشاهده فیلم و سریال کنید.همچنین پیشنهاد میشود به گوش دادن روز حداقل چند موسیقی حال خودتان را بهتر کنید.
                         برای بعضی ها هم کتاب خواندن میتواند مفید باشد که توصیه میشود حداقل روزی 15 دقیقه برای خواندن کتاب وقت بگزارند . <br>
                          بعضی از افراد به جای وقت گزاشتن در شبکه های اجتمایی میتواندد با گوش دادان به پادکست های در زمینه های علمی ورزشی و یا توسعه فردی به رشد خوندشون کمک کنند .پیشنهاد میشود که هنگامی که خسته هستید یا انرژی کافی برای انجام کاری را نداریدوگوش دادن به پادکست به مدت 10 تا 20 دقیقه میتواند نتایج باور نکردنی ای را برای شما به ارمقان آورد. <br></p>
                </div>
            </section>

            <section class="main_categorys" id="category">
                <div class="main_category">
                   <h1 style="margin-bottom: 40px;">چه حسی داری رفیق؟</h1>
                   <div class="category_box_1">
                        <div class="category_row" id="category_row_1">
                            <h2 style="z-index: 3">خوشحالم 😁</h2>
                            <div style="z-index: 2" class="overlay"></div>
                        </div>
                        <div class="category_row" id="category_row_2">
                            <h2 style="z-index: 3">خوبم 🙂</h2>
                            <div style="z-index: 2" class="overlay"></div>
                        </div>
                   </div>
                   <div class="category_box_2">
                    <div class="category_row" id="category_row_3">
                        <h2 style="z-index: 3">ناراحتم 😞</h2>
                        <div style="z-index: 2" class="overlay"></div>
                    </div>
                    <div class="category_row" id="category_row_4">
                        <h2 style="z-index: 3">عصبانیم 😠</h2>
                        <div style="z-index: 2" class="overlay"></div>
                    </div>
                   </div>
                </div>
                <div class="category_img">
                    <img src="{% static 'img/na_january_44.jpg' %}" alt="" class="main_category_img">
                </div>
            </section>
        </div>
    </main>
    {% endblock content%}
{% block script %}
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            const box1 = document.querySelector('#category_row_1');
            const box2 = document.querySelector('#category_row_2');
            const box3 = document.querySelector('#category_row_3');
            const box4 = document.querySelector('#category_row_4');

            box1.addEventListener('click', () => {
                const h1_1 = box1.querySelector('h2');
                const h1_2 = box2.querySelector('h2')
                const h1_3 = box3.querySelector('h2')
                const h1_4 = box4.querySelector('h2')
                h1_1.classList.add('fade-out');
                h1_2.classList.add('fade-out');
                h1_3.classList.add('fade-out');
                h1_4.classList.add('fade-out');
                {% song_random_number 1 as song_random_number1 %}
                    {% book_random_number 1 as book_random_number1 %}
                    {% podcast_random_number 1 as podcast_random_number1 %}
                    {% video_random_number 1 as video_random_number1 %}
                setTimeout(() => {
                    h1_1.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:book_detail' khosh.quality book_random_number1 %}">کتاب</a>';
                    h1_2.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:video_detail' khosh.quality video_random_number1 %}">فیلم</a>';
                    h1_3.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:podcast_detail' khosh.quality podcast_random_number1 %}">پادکست</a>';
                    h1_4.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:music_detail' khosh.quality song_random_number1 %}">آهنگ</a>';
                    h1_1.classList.remove('fade-out');
                    h1_2.classList.remove('fade-out');
                    h1_3.classList.remove('fade-out');
                    h1_4.classList.remove('fade-out');
                    h1_1.classList.add('fade-in');
                    h1_2.classList.add('fade-in');
                    h1_3.classList.add('fade-in');
                    h1_4.classList.add('fade-in');
                }, 250);
            });
            box2.addEventListener('click', () => {
                const h1_1 = box1.querySelector('h2');
                const h1_2 = box2.querySelector('h2')
                const h1_3 = box3.querySelector('h2')
                const h1_4 = box4.querySelector('h2')
                h1_1.classList.add('fade-out');
                h1_2.classList.add('fade-out');
                h1_3.classList.add('fade-out');
                h1_4.classList.add('fade-out');
                setTimeout(() => {
    {% song_random_number 2 as song_random_number1 %}
                    {% book_random_number 2 as book_random_number1 %}
                    {% podcast_random_number 2 as podcast_random_number1 %}
                    {% video_random_number 2 as video_random_number1 %}
                    h1_1.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:book_detail' khoob.quality book_random_number1  %}">کتاب</a>';
                    h1_2.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:video_detail' khoob.quality video_random_number1 %}">فیلم</a>';
                    h1_3.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:podcast_detail' khoob.quality podcast_random_number1 %}">پادکست</a>';
                    h1_4.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:music_detail' khoob.quality song_random_number1 %}">آهنگ</a>';
                    h1_1.classList.remove('fade-out');
                    h1_2.classList.remove('fade-out');
                    h1_3.classList.remove('fade-out');
                    h1_4.classList.remove('fade-out');
                    h1_1.classList.add('fade-in');
                    h1_2.classList.add('fade-in');
                    h1_3.classList.add('fade-in');
                    h1_4.classList.add('fade-in');
                }, 250);
            });
            box3.addEventListener('click', () => {
                const h1_1 = box1.querySelector('h2');
                const h1_2 = box2.querySelector('h2')
                const h1_3 = box3.querySelector('h2')
                const h1_4 = box4.querySelector('h2')
                h1_1.classList.add('fade-out');
                h1_2.classList.add('fade-out');
                h1_3.classList.add('fade-out');
                h1_4.classList.add('fade-out');
                setTimeout(() => {
           {% song_random_number 3 as song_random_number1 %}
                    {% book_random_number 3 as book_random_number1 %}
                    {% podcast_random_number 3 as podcast_random_number1 %}
                    {% video_random_number 3 as video_random_number1 %}
                    h1_1.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:book_detail' na.quality book_random_number1 %}">کتاب</a>';
                    h1_2.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:video_detail' na.quality video_random_number1 %}">فیلم</a>';
                    h1_3.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:podcast_detail' na.quality podcast_random_number1 %}">پادکست</a>';
                    h1_4.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:music_detail' na.quality song_random_number1 %}">آهنگ</a>';
                    h1_1.classList.remove('fade-out');
                    h1_2.classList.remove('fade-out');
                    h1_3.classList.remove('fade-out');
                    h1_4.classList.remove('fade-out');
                    h1_1.classList.add('fade-in');
                    h1_2.classList.add('fade-in');
                    h1_3.classList.add('fade-in');
                    h1_4.classList.add('fade-in');
                }, 250);
            });
            box4.addEventListener('click', () => {
                const h1_1 = box1.querySelector('h2');
                const h1_2 = box2.querySelector('h2')
                const h1_3 = box3.querySelector('h2')
                const h1_4 = box4.querySelector('h2')
                h1_1.classList.add('fade-out');
                h1_2.classList.add('fade-out');
                h1_3.classList.add('fade-out');
                h1_4.classList.add('fade-out');
                setTimeout(() => {
           {% song_random_number 4 as song_random_number1 %}
                    {% book_random_number 4 as book_random_number1 %}
                    {% podcast_random_number 4 as podcast_random_number1 %}
                    {% video_random_number 4 as video_random_number1 %}
                    h1_1.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:book_detail' asab.quality book_random_number1 %}">کتاب</a>';
                    h1_2.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:video_detail' asab.quality video_random_number1 %}">فیلم</a>';
                    h1_3.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:podcast_detail' asab.quality podcast_random_number1 %}">پادکست</a>';
                    h1_4.innerHTML = '<a style="text-decoration: none;color:#fff" href="{% url 'core:music_detail' asab.quality song_random_number1 %}">آهنگ</a>';
                    h1_1.classList.remove('fade-out');
                    h1_2.classList.remove('fade-out');
                    h1_3.classList.remove('fade-out');
                    h1_4.classList.remove('fade-out');
                    h1_1.classList.add('fade-in');
                    h1_2.classList.add('fade-in');
                    h1_3.classList.add('fade-in');
                    h1_4.classList.add('fade-in');
                }, 250);
            });
        });
    </script>
{% endblock script %}
</body>
</html>

core/templates/core/podcast.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
{% block head %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/music.css' %}">
</head>
{% endblock %}
<body>
{% block content %}
    <main class="main">
        <div class="container">
            <section class="books">
                <div class="book">
                    <div class="content">
                        <h1>{{ podcast.name }}</h1>
                        <audio controls>
                            <source src="{{ podcast.audio.url }}" type="audio/mp3">
                            <source src="{{ podcast.audio.url }}" type="audio/mpeg">
                            can't be played
                        </audio>
                    </div>
                    <div class="images">
                        <img class="image" src="{{ podcast.image.url }}" alt="">
                    </div>
                </div>
                <h1 style="margin-top: 5rem;margin-bottom: 3rem;">پادکست های بیشتر</h1>
                <div class="more_books">
                    {% for pod in podcasts %}
                    	<div class="box">
                        <div class="simages">
                            <a href="{% url 'core:podcast_detail' pod.feeling pod.id %}"><img src="{{ pod.image.url }}" alt="podcast" class="simage"></a>
                        </div>
                            <h3>{{ pod.name }}</h3>
{#                        <p style="margin-top: -3px;">{{ pod.description | truncatewords:7 }}</p>#}
                    </div>
                    {% endfor %}

                </div>
            </section>
        </div>
    </main>
{% endblock content%}
    <footer class="footer">
        <div class="container">
            <div class="footer_bottom">
                <div class="footer_right">
                    <h3 class="footer_about_header">اطلاعات تماس</h3>
                    <p class="footer_p"><strong>آدرس:</strong>مازندران-بابل-امامزاده قاسم-هادی 11.1</p>
                    <p class="footer_p"><strong>شماره تماس:</strong>09115673743</p>
                    <p class="footer_p"><strong>ایمیل:</strong>sajjad.kafshgar123@gmail.com</p>
                </div>
                <div class="footer_left">
                    <div><img src="" alt="" class="footer img"></div>
                    <div class="flex">
                        <div class="footer_contact_platforms"> </div>
                        <div class="footer_logos"><img src="./imgs/1.png" alt="" class="footer_logo"></div>
                    </div>
                    <div class="footer_contact_about"><p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در </p></div>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

core/templates/core/song.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
{% block head %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/music.css' %}">
</head>
{% endblock %}
<body>
    {% block content %}
    <main class="main">
        <div class="container">
            <section class="books">
                <div class="book">
                    <div class="content">
                        <h1>{{ song.name }}</h1>
                        <h2>{{ song.singer }}</h2>
                        <audio controls id="audioPlayer" preload="auto">
                            <source src="{{ song.audio.url }}" type="audio/ogg">
                            <source src="{{ song.audio.url }}" type="audio/mp3">
                            can't be played
                        </audio>
                    </div>
                    <div class="images">
                        <img class="image" src="{{ song.image.url }}" alt="">
                    </div>
                </div>
                <h1 style="margin-top: 5rem;margin-bottom: 3rem;">آهنگ های بیشتر</h1>
                <div class="more_books">
                    {% for son in songs %}
                    <div class="box">
                        <div class="simages">
                            <a href="{% url 'core:music_detail' son.feeling son.id %}"><img src="{{ son.image.url }}" alt="song" class="simage"></a>
                        </div>
                        <h3>{{ son.name }}</h3>
                        <p style="margin-top: -3px;">{{ son.singer }}</p>
                    </div>
                    {% endfor %}
                </div>
            </section>
        </div>
    </main>
{% endblock content %}

    <footer class="footer">
        <div class="container">
            <div class="footer_bottom">
                <div class="footer_right">
                    <h3 class="footer_about_header">اطلاعات تماس</h3>
                    <p class="footer_p"><strong>آدرس:</strong>مازندران-بابل-امامزاده قاسم-هادی 11.1</p>
                    <p class="footer_p"><strong>شماره تماس:</strong>09115673743</p>
                    <p class="footer_p"><strong>ایمیل:</strong>sajjad.kafshgar123@gmail.com</p>
                </div>
                <div class="footer_left">
                    <div><img src="" alt="" class="footer img"></div>
                    <div class="flex">
                        <div class="footer_contact_platforms"> </div>
                        <div class="footer_logos"><img src="./imgs/1.png" alt="" class="footer_logo"></div>
                    </div>
                    <div class="footer_contact_about"><p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در </p></div>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

core/templates/core/video.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
{% block head %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/video.css' %}">
</head>
{% endblock %}
<body>
   {% block content %}
    <main class="main">
        <div class="container">
            <section class="books">
                <div class="book">
                    <div class="content">
                        <h1>{{ video.name }}</h1>
                        <p>{{ video.description }}</p>
                    </div>
                    <div class="images">
                        <video controls class="simage">
                            <source src="{{ video.video.url }}" type="video/mp4">
                            <source src="{{ video.video.url }}" type="video/webm">
                            this video cant be played
                        </video>
                    </div>
                </div>
                <h1 style="margin-top: 5rem;margin-bottom: 3rem;">ویدئو های بیشتر</h1>
                <div class="more_books">
                    {% for vid in videos %}
                    <div class="box">
                        <div class="simages">
                            <a href="{% url 'core:video_detail' vid.feeling vid.id %}"><img src="{{ vid.image.url }}" alt="video" class="simage"></a>
                        </div>
                        <h3>{{ vid.name }}</h3>
{#                        <p style="margin-top: -3px;">{{ vid.description | truncatewords:7 }}</p>#}
                    </div>
                    {% endfor %}

                </div>
            </section>
        </div>
    </main>
{% endblock %}

</body>
</html>